# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Natalia Ivanova
email: TaliaIvaVoice@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.taliaiva.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll
youtube_channel: "UCtStp5Cgjl_rVvPUDLvr3Fw"
facebook_page: "natalia.ivanova.779642"
instagram_page: "taliaiva"

# Build settings
markdown: kramdown

# Google services
#google_analytics: UA-100838240-1

t:
  en:
    about:
      name: "About"
      url: "/about-en.html"
    pictures:
      name: "Pictures"
      url: "/pictures-en.html"
    video:
      name: "Video"
      url: "/video-en.html"
    vocal-coaching:
      name: "Vocal Coaching"
      url: "/vocal-coaching-en.html"
    projects:
      name: "Projects"
      url: "/projects-en.html"
    contact:
      name: "Contact"
      url: "/contact-en.html"
  ru:
    about:
      name: "Биография"
      url: "/биография-ru.html"
    pictures:
      name: "Фотографии"
      url: "/фотографии-ru.html"
    video:
      name: "Видео"
      url: "/видео-ru.html"
    vocal-coaching:
      name: "Уроки вокала"
      url: "/уроки-вокала.html"
    projects:
      name: "Проекты"
      url: "/проекты-ru.html"
    contact:
      name: "Контакт"
      url: "/контакт-ru.html"
  nl:
    about:
      name: "Biografie"
      url: "/biografie-nl.html"
    pictures:
      name: "Foto’s"
      url: "/foto’s-nl.html"
    video:
      name: "Video’s"
      url: "/video’s-nl.html"
    vocal-coaching:
      name: "Zang Coaching"
      url: "/zang-coaching-nl.html"
    projects:
      name: "Projecten"
      url: "/projecten-nl.html"
    contact:
      name: "Contact"
      url: "/contact-nl.html"


home:
  en:
    home:    
      url: "/home-en.html"
  ru:
    home:
      url: "главная-ru.html"
  nl:
    home:
      url: "home-nl.html"
